author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: Task-Email-PEP-NoStore
no_index: 
  directory: 
    - inc
    - t
requires: 
  Bundle::Email: 0.040
  Email::Abstract: 2.13
  Email::Address: 1.86
  Email::Date: 1.101
  Email::Delete: 1.02
  Email::Filter: 1.03
  Email::Folder: 0.851
  Email::Folder::IMAP: 1.10
  Email::Folder::IMAPS: 1.10
  Email::Folder::POP3: 1.011
  Email::FolderType: 0.7
  Email::FolderType::Net: 1.04
  Email::LocalDelivery: 0.21
  Email::LocalDelivery::Ezmlm: 0.10
  Email::MIME: 1.85
  Email::MIME::Attachment::Stripper: 1.311
  Email::MIME::ContentType: 1.01
  Email::MIME::Creator: 1.45
  Email::MIME::Encodings: 1.31
  Email::MIME::Modifier: 1.43
  Email::MessageID: 1.35
  Email::Reply: 1.20
  Email::Send: 2.171
  Email::Simple: 1.96
  Email::Simple::Creator: 1.41
  Email::Simple::FromHandle: 0.011
  Email::Simple::Headers: 1.02
  Email::Store: 0.25
  Email::Store::HTML: 0.301
  Email::Store::Plucene: 0.02
  Email::Store::Summary: 1.3
  Email::Store::Thread: 1.1
  Email::Stuff: 2.03
  Email::Thread: 0.71
  Email::Valid: 0.176
  Mail::Audit: 2.203
  Mail::DeliveryStatus::BounceParser: 1.512
  Mail::LocalDelivery: 0.301
version: 6212.235
